sudo: required

services:
  - docker

script:
  - make base
  - make android-arm
  - make android-x64
  - make darwin-x64
  - make linux-x86
  - make linux-x64
  - make linux-arm
  - make windows-x86
  - make windows-x64
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make push || false'
