sudo: required

services:
  - docker

script:
  - make all
  # - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # - docker tag cross-compiler quasarhq/cross-compiler
  # - docker push quasarhq/cross-compiler
