sudo: required

services:
  - docker

env:
  - PLATFORM=android-arm
  - PLATFORM=android-x64
  - PLATFORM=darwin-x64
  - PLATFORM=linux-x86
  - PLATFORM=linux-x64
  - PLATFORM=linux-arm
  - PLATFORM=windows-x86
  - PLATFORM=windows-x64

before_script:
  - make base

script:
  - make $PLATFORM
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make push || true'
